version: "3"

services: 
  web:
    container_name: exampleapp
    restart: always
    build: .
    ports: 
        - "5000:3000"
    links: 
        - mongo
  mongo:
    container_name: mymongo
    image: mongo
    ports: 
        - "27018:27017"